name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  # to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: pip install huggingface_hub
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          python -c '
          import os
          from huggingface_hub import login, create_repo, upload_folder

          # Login with your Hugging Face credentials
          login(token=os.environ.get("HF_TOKEN"))

          print("Uploading to Model Repository...")
          create_repo("tapiocaTakeshi/Qubit", repo_type="model", exist_ok=True)
          upload_folder(
              folder_path=".",
              repo_id="tapiocaTakeshi/Qubit",
              repo_type="model",
              commit_message="Sync repository files to model repo via GitHub Actions"
          )

          print("Uploading to Space Repository...")
          create_repo("tapiocaTakeshi/Qubit", repo_type="space", exist_ok=True)
          upload_folder(
              folder_path=".",
              repo_id="tapiocaTakeshi/Qubit",
              repo_type="space",
              commit_message="Sync repository files to space repo via GitHub Actions"
          )
          '
